version: '3.3'

services:
  mariadb:
    container_name: usjt-mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: usjt
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    container_name: usjt-phpmyadmin
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=usjt
